import type { Metadata } from 'next'

import { Wrapper } from '@/modules/core/ui/wrapper'
import Link from 'next/link'

import './globals.css'

export const metadata: Metadata = {
  description: 'Generated by create next app',
  title: 'Create Next App',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body>
        <header className='sticky top-0 z-10 bg-primary py-5 text-primary-foreground shadow'>
          <Wrapper>
            <nav className=''>
              <Link className='text-2xl font-bold' href='/'>
                Movie App
              </Link>
            </nav>
          </Wrapper>
        </header>
        {children}
      </body>
    </html>
  )
}
